package org.sybila.ode;

/**
 * A set of simulations generated by a simulation launcher
 * 
 * @author Jan Papousek
 */
public interface SimulationResult
{

	/**
	 * It returns a number of generated simulations
	 */
	int getNumberOfSimulations();

	/**
	 * It returns a simulation with the given id (started form 0).
	 *
	 * @throws IllegalArgumentException if the simulation id is out the range
	 */
	Simulation getSimulation(int simulationId);

}
