package org.sybila.ode;

/**
 * This class represents a status of the simulation which is generated by
 * a simulation launcher.
 *
 * @author Jan Papousek
 */
public enum SimulationStatus
{

	OK, TIMEOUT, PRECISION;

	/**
	 * It converts an integer to the simulation status
	 * @throws IllegalArgumentException if the given integer doesn't correspond
	 * to any simulation status
	 */
	public static SimulationStatus fromInt(int status) {
		switch(status) {
			case 0:
				return OK;
			case 1:
				return TIMEOUT;
			case 2:
				return PRECISION;
			default:
				//return null;
				throw new IllegalStateException("There is no status corresponding to the number [" + status + "].");
		}
	}

}
